# Generated by Django 5.1.7 on 2025-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TCheckouts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkout_date', models.DateField()),
                ('checkout_no', models.CharField(max_length=20)),
                ('PartNo', models.CharField(max_length=15)),
                ('TestItem', models.CharField(max_length=50, null=True)),
                ('checkout_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SN', models.TextField()),
                ('DC', models.CharField(max_length=8)),
                ('REV', models.CharField(max_length=10)),
                ('Work_Order', models.CharField(max_length=40)),
                ('Remarks', models.TextField(null=True)),
                ('checkout_status', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('JobNo', models.IntegerField()),
                ('QRT', models.BooleanField(default=False)),
                ('Product', models.CharField(max_length=25)),
                ('Customer', models.CharField(max_length=15)),
                ('PartNo', models.CharField(max_length=25)),
                ('Stage', models.CharField(max_length=5)),
                ('TestItem', models.CharField(max_length=50)),
                ('SampleSize', models.IntegerField()),
                ('TestPeriod', models.IntegerField()),
                ('Owner', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Status', models.CharField(max_length=10)),
                ('Upload_Elab', models.BooleanField(null=True)),
                ('Remark', models.TextField(null=True)),
            ],
        ),
    ]
