# Generated by Django 5.1.7 on 2025-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcheckouts',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='SN',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='TestItem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Upload_Elab',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
