# Generated by Django 5.1.7 on 2025-06-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0002_alter_tcheckouts_remarks_alter_tcheckouts_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcheckouts',
            name='DC',
            field=models.CharField(max_length=8, verbose_name='周期'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='PartNo',
            field=models.CharField(max_length=15, verbose_name='机种名称'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='REV',
            field=models.CharField(max_length=10, verbose_name='版本'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='Remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='SN',
            field=models.TextField(unique=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='TestItem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试项目'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='Work_Order',
            field=models.CharField(max_length=40, verbose_name='工令'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_date',
            field=models.DateField(verbose_name='领用日期'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_no',
            field=models.CharField(max_length=20, verbose_name='领用单号'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_qty',
            field=models.IntegerField(verbose_name='领出数量'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_status',
            field=models.CharField(blank=True, choices=[(1, '已领用'), (2, '未领用'), (3, '已归还')], max_length=20, null=True, verbose_name='领出状态'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Customer',
            field=models.CharField(max_length=15, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='EndDate',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='JobNo',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Owner',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='PartNo',
            field=models.CharField(max_length=25, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Product',
            field=models.CharField(max_length=25, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='QRT',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Remark',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='SampleSize',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Stage',
            field=models.CharField(max_length=5, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='StartDate',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Status',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='TestItem',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='TestPeriod',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Upload_Elab',
            field=models.BooleanField(blank=True, null=True, verbose_name=''),
        ),
    ]
