# Generated by Django 5.1.7 on 2025-06-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0003_alter_tcheckouts_dc_alter_tcheckouts_partno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcheckouts',
            name='SN',
            field=models.TextField(verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_status',
            field=models.CharField(blank=True, choices=[(1, '未领用'), (2, '已领用'), (3, '已归还')], max_length=20, null=True, verbose_name='领出状态'),
        ),
    ]
