# Generated by Django 5.1.7 on 2025-06-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0004_alter_tcheckouts_sn_alter_tcheckouts_checkout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_status',
            field=models.IntegerField(blank=True, choices=[(1, '未领用'), (2, '已领用'), (3, '已归还')], max_length=20, null=True, verbose_name='领出状态'),
        ),
    ]
