# Generated by Django 5.1.7 on 2025-06-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0005_alter_tcheckouts_checkout_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcheckouts',
            name='SN',
            field=models.TextField(unique=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='领用单号'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='checkout_status',
            field=models.IntegerField(blank=True, choices=[(1, '未领用'), (2, '已领用'), (3, '已归还')], null=True, verbose_name='领出状态'),
        ),
    ]
