# Generated by Django 5.1.7 on 2025-06-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0006_alter_tcheckouts_sn_alter_tcheckouts_checkout_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tschedule',
            name='Customer',
            field=models.CharField(max_length=15, verbose_name='客户别'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='EndDate',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='JobNo',
            field=models.CharField(max_length=20, unique=True, verbose_name='工作编号'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Owner',
            field=models.CharField(max_length=50, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='PartNo',
            field=models.CharField(max_length=25, verbose_name='机种名'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Product',
            field=models.CharField(max_length=25, verbose_name='产品别'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='QRT',
            field=models.BooleanField(choices=[(False, '领用'), (True, '送测')], default=False, verbose_name='送测'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='SampleSize',
            field=models.IntegerField(verbose_name='样品数'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Stage',
            field=models.IntegerField(choices=[(1, 'MP'), (2, 'MVT'), (3, 'DVT'), (4, 'EVT')], default=1, verbose_name='阶段'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='StartDate',
            field=models.DateField(verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Ongoing'), (2, 'Close'), (3, 'Pending')], default=1, verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='TestItem',
            field=models.CharField(max_length=50, verbose_name='测试项目'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='TestPeriod',
            field=models.IntegerField(verbose_name='试验时间'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Upload_Elab',
            field=models.BooleanField(blank=True, choices=[(False, '未上传'), (True, '已上传')], default=False, null=True, verbose_name='上传系统'),
        ),
    ]
