# Generated by Django 5.1.7 on 2025-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0008_alter_tschedule_customer_alter_tschedule_partno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tschedule',
            name='PartNo',
            field=models.CharField(max_length=15, verbose_name='机种名'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Product',
            field=models.IntegerField(choices=[(0, 'Adapter'), (1, 'Desk top'), (2, 'Sever'), (3, 'OP'), (4, 'Charger'), (5, 'LED'), (6, 'VRM'), (10, 'HSR'), (22, 'DC/DC')], default=1, verbose_name='产品别'),
        ),
    ]
