# Generated by Django 5.1.7 on 2025-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0009_alter_tschedule_partno_alter_tschedule_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tschedule',
            name='Customer',
            field=models.IntegerField(choices=[(0, 'NA'), (0, 'HP'), (1, 'IBM'), (2, 'WISTRON'), (3, '杭州協能科技'), (4, 'LITEON'), (5, 'NCR'), (6, 'POWER'), (7, 'ACER'), (8, 'MITAC'), (9, 'HITACHI'), (10, 'ADB'), (11, 'FUJITSU'), (12, 'NEC'), (13, 'FLYTEC'), (14, 'DELL'), (15, 'PHILIPS'), (16, 'DIEBOLD'), (17, 'APPLE'), (18, 'MOTOTECH'), (19, 'CALCOMP'), (20, 'DOT  HILL'), (21, 'COMPAL'), (22, 'MSI'), (23, 'LG'), (24, 'SUPERMICRO'), (25, 'JUNIPER'), (26, 'PLC'), (27, 'AIC'), (28, 'ZT'), (29, 'BE'), (30, 'FIC'), (31, 'INVENTEC'), (32, 'JOYTECH'), (33, 'CANON'), (34, 'SCHNEIDER'), (35, 'AMWAY'), (36, 'CORNING'), (37, 'EMC&DELL'), (38, 'NOKIA'), (39, 'CISCO'), (40, 'QSAN'), (41, '迎廣'), (42, '曙光'), (43, '永大機電'), (44, 'INFOACTION'), (45, 'ERICSSON'), (46, 'SHARP'), (47, 'NEWTECH'), (48, 'GOOGLE'), (49, 'QUANTA'), (50, 'WAMCO'), (51, 'GTECH'), (52, '海康威視'), (53, 'TOSHIBA'), (54, 'CELESTICA'), (55, 'TECHNICOLOR'), (56, '中華電信'), (57, 'NORTEL'), (59, 'DJI'), (60, 'COMPUWARE'), (61, 'ANDREW'), (62, 'TIVO'), (63, 'ARRIS'), (64, 'MITEL'), (65, 'GIGABYTE'), (66, 'EPSON'), (67, 'ARAS'), (68, 'PACE'), (69, 'COMTREND'), (70, 'LEA'), (71, 'FLEXTRONICS'), (72, 'LENOVO'), (73, 'CLOUD'), (74, 'AMZ'), (75, 'CIENA'), (76, 'ICON'), (77, 'GOGORO'), (78, 'GOOXI'), (79, '宸圓科技'), (80, '比特大陸'), (81, 'DAHUA'), (82, 'HPE'), (83, 'OPTEX'), (84, 'EILI'), (85, 'DLH'), (86, 'ANTEC'), (87, 'TARGUS'), (88, 'ASUS')], default=0, verbose_name='客户别'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Product',
            field=models.IntegerField(choices=[(0, 'NA'), (0, 'Adapter'), (1, 'Desk top'), (2, 'Sever'), (3, 'OP'), (4, 'Charger'), (5, 'LED'), (6, 'VRM'), (10, 'HSR'), (22, 'DC/DC')], default=0, verbose_name='产品别'),
        ),
    ]
