# Generated by Django 5.1.7 on 2025-06-16 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0010_alter_tschedule_customer_alter_tschedule_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCustCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_code', models.CharField(max_length=10, unique=True, verbose_name='客户代码')),
                ('cust_name', models.CharField(max_length=50, verbose_name='客户名称')),
            ],
        ),
        migrations.CreateModel(
            name='TProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=10, unique=True, verbose_name='产品代码')),
                ('product_type', models.CharField(max_length=20, verbose_name='产品类型')),
            ],
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORTplans.tcustcode', verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORTplans.tproducttype', verbose_name='产品类型'),
        ),
    ]
