# Generated by Django 5.1.7 on 2025-06-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0011_tcustcode_tproducttype_alter_tschedule_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTechnician',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tech_code', models.CharField(max_length=10, unique=True, verbose_name='工号')),
                ('tech_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('tech_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('tech_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
            ],
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='Owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='SampleSize',
            field=models.IntegerField(default=1, verbose_name='样品数'),
        ),
        migrations.CreateModel(
            name='TTestItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_item', models.CharField(max_length=50, unique=True, verbose_name='测试项目')),
                ('test_time', models.IntegerField(verbose_name='测试时间(h)')),
                ('Remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('test_owner', models.ManyToManyField(blank=True, related_name='test_owner', to='ORTplans.ttechnician', verbose_name='测试负责人')),
            ],
        ),
        migrations.AlterField(
            model_name='tschedule',
            name='TestItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORTplans.ttestitem', verbose_name='测试项目'),
        ),
    ]
