# Generated by Django 5.1.7 on 2025-06-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0012_ttechnician_alter_tschedule_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttestitem',
            name='dispose',
            field=models.BooleanField(choices=[(True, '回线'), (False, '报废')], default=False, verbose_name='样品处理'),
        ),
    ]
