# Generated by Django 5.1.7 on 2025-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0013_ttestitem_dispose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttestitem',
            name='dispose',
            field=models.BooleanField(choices=[(False, '报废'), (True, '回线')], default=False, verbose_name='样品处理'),
        ),
        migrations.RemoveField(
            model_name='ttestitem',
            name='test_owner',
        ),
        migrations.AddField(
            model_name='ttestitem',
            name='test_owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='测试负责人'),
        ),
    ]
