# Generated by Django 5.1.7 on 2025-06-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0014_alter_ttestitem_dispose_remove_ttestitem_test_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttestitem',
            name='dispose',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='样品处理'),
        ),
    ]
