# Generated by Django 5.1.7 on 2025-06-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0015_alter_ttestitem_dispose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttestitem',
            name='test_time',
            field=models.FloatField(verbose_name='测试时间(h)'),
        ),
    ]
