# Generated by Django 5.1.7 on 2025-06-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0016_alter_ttestitem_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttestitem',
            name='dispose',
            field=models.CharField(blank=True, choices=[('回线', '回线'), ('报废', '报废')], max_length=25, null=True, verbose_name='样品处理'),
        ),
    ]
