# Generated by Django 5.1.7 on 2025-06-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0017_alter_ttestitem_dispose'),
    ]

    operations = [
        migrations.AddField(
            model_name='tschedule',
            name='Work_Order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ORTplans.tcheckouts', verbose_name='工令'),
        ),
        migrations.AlterField(
            model_name='tcheckouts',
            name='Work_Order',
            field=models.CharField(max_length=40, unique=True, verbose_name='工令'),
        ),
    ]
