# Generated by Django 5.1.7 on 2025-06-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0018_tschedule_work_order_alter_tcheckouts_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tschedule',
            name='Work_Order',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='工令'),
        ),
    ]
