# Generated by Django 5.1.7 on 2025-06-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORTplans', '0019_alter_tschedule_work_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcheckouts',
            name='TestItem',
        ),
    ]
