# Generated by Django 5.1.7 on 2025-06-25 15:09

import ORTplans.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ORTplans", "0021_tcheckouts_sn_file_alter_tcheckouts_dc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tcheckouts",
            name="DC",
            field=models.CharField(max_length=8, verbose_name="周期"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="PartNo",
            field=models.CharField(max_length=15, verbose_name="机种名称"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="REV",
            field=models.CharField(max_length=10, verbose_name="版本"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="Remarks",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="SN",
            field=models.TextField(blank=True, null=True, verbose_name="序列号"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="Work_Order",
            field=models.CharField(max_length=40, unique=True, verbose_name="工令"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="checkout_date",
            field=models.DateField(verbose_name="领用日期"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="checkout_no",
            field=models.CharField(max_length=20, unique=True, verbose_name="领用单号"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="checkout_qty",
            field=models.IntegerField(verbose_name="领出数量"),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="checkout_status",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "未领用"), (2, "已领用"), (3, "已归还")],
                default=2,
                null=True,
                verbose_name="领出状态",
            ),
        ),
        migrations.AlterField(
            model_name="tcheckouts",
            name="sn_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=ORTplans.models.RenameSNFile("checkouts/sn_files/"),
                verbose_name="序列号文件",
            ),
        ),
        migrations.AlterField(
            model_name="tcustcode",
            name="cust_code",
            field=models.CharField(max_length=10, unique=True, verbose_name="客户代码"),
        ),
        migrations.AlterField(
            model_name="tcustcode",
            name="cust_name",
            field=models.CharField(max_length=50, verbose_name="客户名称"),
        ),
        migrations.AlterField(
            model_name="tproducttype",
            name="product_code",
            field=models.CharField(max_length=10, unique=True, verbose_name="产品代码"),
        ),
        migrations.AlterField(
            model_name="tproducttype",
            name="product_type",
            field=models.CharField(max_length=20, verbose_name="产品类型"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ORTplans.tcustcode",
                verbose_name="客户名称",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="EndDate",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="JobNo",
            field=models.CharField(max_length=20, unique=True, verbose_name="工作编号"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Owner",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="负责人"
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="PartNo",
            field=models.CharField(max_length=15, verbose_name="机种名"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ORTplans.tproducttype",
                verbose_name="产品类型",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="QRT",
            field=models.BooleanField(
                choices=[(False, "领用"), (True, "送测")],
                default=False,
                verbose_name="送测",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="SampleSize",
            field=models.IntegerField(default=3, verbose_name="样品数"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Stage",
            field=models.IntegerField(
                choices=[(1, "MP"), (2, "MVT"), (3, "DVT"), (4, "EVT")],
                default=1,
                verbose_name="阶段",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="StartDate",
            field=models.DateField(verbose_name="开始日期"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Status",
            field=models.IntegerField(
                choices=[(1, "Ongoing"), (2, "Close"), (3, "Pending")],
                default=1,
                verbose_name="完成状态",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="TestItem",
            field=models.ForeignKey(
                blank=True,
                default=29,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ORTplans.ttestitem",
                verbose_name="测试项目",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="TestPeriod",
            field=models.IntegerField(verbose_name="试验时间"),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Upload_Elab",
            field=models.BooleanField(
                blank=True,
                choices=[(False, "未上传"), (True, "已上传")],
                default=False,
                null=True,
                verbose_name="上传系统",
            ),
        ),
        migrations.AlterField(
            model_name="tschedule",
            name="Work_Order",
            field=models.CharField(
                blank=True, max_length=40, null=True, unique=True, verbose_name="工令"
            ),
        ),
        migrations.AlterField(
            model_name="ttechnician",
            name="tech_code",
            field=models.CharField(max_length=10, unique=True, verbose_name="工号"),
        ),
        migrations.AlterField(
            model_name="ttechnician",
            name="tech_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="ttechnician",
            name="tech_name",
            field=models.CharField(max_length=50, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="ttechnician",
            name="tech_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="电话"
            ),
        ),
        migrations.AlterField(
            model_name="ttestitem",
            name="Remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="ttestitem",
            name="dispose",
            field=models.CharField(
                blank=True,
                choices=[("回线", "回线"), ("报废", "报废")],
                max_length=25,
                null=True,
                verbose_name="样品处理",
            ),
        ),
        migrations.AlterField(
            model_name="ttestitem",
            name="test_item",
            field=models.CharField(max_length=50, unique=True, verbose_name="测试项目"),
        ),
        migrations.AlterField(
            model_name="ttestitem",
            name="test_owner",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="测试负责人"
            ),
        ),
        migrations.AlterField(
            model_name="ttestitem",
            name="test_time",
            field=models.FloatField(verbose_name="测试时间(h)"),
        ),
    ]
